# Generated by Django 4.1.1 on 2023-02-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='article_name',
            new_name='article',
        ),
    ]
