# Generated by Django 4.1.1 on 2023-02-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_article_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('article', 'city')},
        ),
    ]
