# Generated by Django 4.1.1 on 2023-02-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_alter_storage_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.article')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.storage')),
            ],
        ),
    ]
