# Generated by Django 4.1.1 on 2023-02-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='article',
        ),
    ]
