# Generated by Django 4.1.1 on 2023-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_remove_transaction_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(default='withdraw', max_length=64),
        ),
    ]
