# Generated by Django 4.1.1 on 2023-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_alter_transaction_date_alter_transaction_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='amount',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
